
//geomitrive stuff
import geomerative.*;


import processing.opengl.*;
import java.util.*;
import peasy.*;
import peasy.org.apache.commons.math.*;
import peasy.org.apache.commons.math.geometry.*;
import peasy.test.*;
//
/**
  * This sketch demonstrates how to use an FFT to analyze
  * the audio being generated by an AudioPlayer.
  * <p>
  * FFT stands for Fast Fourier Transform, which is a 
  * method of analyzing audio that allows you to visualize 
  * the frequency content of a signal. You've seen 
  * visualizations like this before in music players 
  * and car stereos.
  * <p>
  * For more information about Minim and additional features, 
  * visit http://code.compartmental.net/minim/
  */

import ddf.minim.analysis.*;
import ddf.minim.*;

Minim       minim;
AudioPlayer jingle;
FFT         fft;
BeatDetect beat;
PeasyCam camera;
Psphere psphere;
Lines line;
Spiral spiral;
Ball ball;
Spect spect;
Circle circle;
Circle msphere;
Waterfall w;
BoxSpiral boxSpiral;

int i=0;
ArrayList<Showable> visuals = new ArrayList<Showable>();




void setup()
{ 
  
  
   
   RG.init(this);
  colorMode(RGB);
  size(512, 200, OPENGL);
  //make all the objects
  camera = new PeasyCam(this, 0, 0, 0, 600);
  
  minim = new Minim(this);
  beat = new BeatDetect();
  psphere = new Psphere(200);
  line = new Lines();
  spiral= new Spiral();
  ball = new Ball();
  spect = new Spect();
  circle = new Circle();
  msphere= new Circle(180,color(255,0,255,52));
  w= new Waterfall();
   spiral = new Spiral();
   boxSpiral= new BoxSpiral();
  Collections.addAll(visuals,circle,spect,line,ball,msphere,w,spiral,psphere,boxSpiral);
  
  jingle = minim.loadFile("The Robots.mp3", 1024);
  //jingle = minim.loadFile("Cissy Strut.mp3", 1024);
  //jingle = minim.loadFile("Autobahn.mp3", 1024);
  //jingle = minim.loadFile("05 - Lectro Spektral Daze - Farther From Ordinary Reality.mp3", 1024);
  jingle.loop();
  fft = new FFT( jingle.bufferSize(), jingle.sampleRate() );
  lights();
}

void draw()
{
   visuals.get(i).show();
  
}

void keyPressed(){
  
  if(key=='a'&& i>0){
   i--; 
    
  }
  else if(key=='d'&&i<visuals.size()-1){
    
   i++; 
  }
  
  
}

void stop()
{
  jingle.close();
  minim.stop();
  super.stop();
  
}
    
  
  